name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics

    - name: Test with pytest
      run: |
        pytest -v > pytest_report.log

    - name: Create Issue on Failure
      if: failure()
      run: |
        cat pytest_report.log
        BODY=$(cat pytest_report.log | jq -aRs .)
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Cristian-code24/ciberseguridad-netwatcher/issues \
          -d "{\"title\":\"CI Failure Report\",\"body\":$BODY}"
